### ISSUE TITLE
test scripts for DeepDPM.py

### ISSUE THREAD

**Issue by Pro-xiaowen** [BGU-CS-VIL/DeepDPM#1]
I haved got my pretrained model(ckpt)using DeepDPM.py, but  I wonder how I can get the inference results (cluster results for some data)using my pretrained ckpt, cloud you share the inference scripts for DeepDPM.py? thanks!

**Comment by meitarronen** [comment]
Sure!
We will upload an inference script soon...

**Comment by Pro-xiaowen** [comment]
已收到祝好许晓文

**Comment by meitarronen** [comment]
Uploaded an example for loading from checkpoint and inference for DeepDPM.
Please see scripts/DeepDPM_load_from_checkpoint.py

**Comment by saitejakokkonda** [comment]
Hey @meitarronen, got .pth.tar file using DeepDPM_alternations.py. Can we get an inference script to load and test the .pth.tar file please ? Thanks.

**Comment by Pro-flynn** [comment]
已收到祝好许晓文

**Comment by saitejakokkonda** [comment]
> 已收到祝好许晓文

Not able to understand, could you please translate to english

**Comment by huitang96** [comment]
> Hey @meitarronen, got .pth.tar file using DeepDPM_alternations.py. Can we get an inference script to load and test the .pth.tar file please ? Thanks.

The same question, All Code:
# LOAD MODEL FROM CHECKPOINT
cp_path = "xxx/default_exp/alt_2_checkpoint.pth.tar"
cp_state = torch.load(cp_path)
data_dim = 124
K = cp_state['K']
hyper_param = cp_state['cluster_net_opt']
args = argparse.Namespace()
for key, value in hyper_param.items():
    setattr(args, key, value)
model = ClusterNetModel.load_from_checkpoint(
    checkpoint_path=cp_path,
    input_dim=data_dim,
    init_k = K,
    hparams=args 
    )

I print out all the keys in this dictionary,

for key in cp_state.keys():
    print(key)

and the resulting content is as follows：
"cluster_net_opt , subcluster_net_opt , model, K, epoch , alt_num"
I use:

K = cp_state['K']
hyper_param = cp_state['cluster_net_opt']
args = argparse.Namespace()
for key, value in hyper_param.items():
    setattr(args, key, value)
model = ClusterNetModel.load_from_checkpoint(
    checkpoint_path=cp_path,
    input_dim=data_dim,
    init_k = K,
    hparams=args
    )

it will comeout: 
AttributeError: Missing attribute "seed"

**Comment by Pro-flynn** [comment]
已收到祝好许晓文
