### ISSUE TITLE
inference example

### ISSUE THREAD

**Issue by imranmu** [BGU-CS-VIL/DeepDPM#10]
Running the inference gives this output. Can we give a set of images as input and then it gives which cluster it belongs to.
`python scripts/DeepDPM_load_from_checkpoint.py `
Sequential()
[tensor([3, 2, 2, 0, 2, 1, 1, 1, 3, 2, 0, 0, 3, 0, 1, 2, 3, 5, 0, 3, 3, 2, 1, 2,
        5, 3, 2, 2, 5, 2, 1, 3, 2, 2, 4, 0, 3, 2, 4, 2, 1, 0, 0, 3, 3, 4, 1, 1,
        2, 5, 2, 2, 0, 0, 4, 0, 3, 2, 5, 0, 0, 2, 1, 2, 4, 3, 2, 0, 0, 3, 5, 2,
        2, 1, 5, 2, 2, 2, 3, 2, 2, 0, 0, 3, 0, 1, 0, 0, 4, 2, 3, 1, 2, 3, 2, 1,
        2, 3, 0, 2, 0, 2, 0, 5, 0, 2, 1, 5, 2, 3, 2, 5, 0, 2, 4, 0, 1, 3, 0, 1,
        3, 1, 0, 2, 5, 2, 0, 2]), 

What should be output of inference

**Comment by meitarronen** [comment]
Hi,
The values in the last printed tensor are the **hard** assignments for each input (you can change it quite easily to soft assignments if needed).
For example, the cluster label of the first example is 3, and the second is 2.
Does that answer your question?

**Comment by kurianbenoy-sentient** [comment]
@imranmu how did you pass the images to inference here?

**Comment by hafsaEn** [comment]
What is the command you used to run the inference document please?

**Comment by imranmu** [comment]
@hafsaEn python scripts/DeepDPM_load_from_checkpoint.py

**Comment by hafsaEn** [comment]
Thank you @imranmu , I tried the same to do inference on mnist, but I get the following error:

`Traceback (most recent call last): File "/home/hafsa/DeepDPM/DeepDPM_load_from_checkpoint.py", line 30, in <module> model = ClusterNetModel.load_from_checkpoint( File "/home/hafsa/.conda/envs/deepdpm/lib/python3.10/site-packages/pytorch_lightning/core/saving.py", line 157, in load_from_checkpoint model = cls._load_model_state(checkpoint, strict=strict, **kwargs) File "/home/hafsa/.conda/envs/deepdpm/lib/python3.10/site-packages/pytorch_lightning/core/saving.py", line 205, in _load_model_state model.load_state_dict(checkpoint['state_dict'], strict=strict) File "/home/hafsa/.conda/envs/deepdpm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1497, in load_state_dict raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format( RuntimeError: Error(s) in loading state_dict for ClusterNetModel: size mismatch for cluster_net.class_fc1.weight: copying a param with shape torch.Size([50, 10]) from checkpoint, the shape in current model is torch.Size([50, 784]). size mismatch for subclustering_net.class_fc1.weight: copying a param with shape torch.Size([50, 10]) from checkpoint, the shape in current model is torch.Size([50, 784]).
`
have you came across the same error? or can you please share the content of the file scripts/DeepDPM_load_from_checkpoint.py?

**Comment by frytoli** [comment]
> Hi, The values in the last printed tensor are the **hard** assignments for each input (you can change it quite easily to soft assignments if needed). For example, the cluster label of the first example is 3, and the second is 2. Does that answer your question?

Hi @meitarronen - I'm coming across the same thing as the OP, and it looks like `scripts/DeepDPM_load_from_checkpoint.py` outputs the hard assignments for *each* value in the input dimension. For example, I'm attempting to cluster input tensors of size 512x512 and the inference output I'm getting from your script for each input is an array of 512 hard-predicted cluster values. A dataset of 32 512x512 input tensors yields an output that is a list of 32 arrays of length 512 (of ). Your inference code is straight forward, and I can't find any issues with it. Am I missing something?

Thanks in advance!
