### ISSUE TITLE
Training on Custom Dataset

### ISSUE THREAD

**Issue by Neltherion** [BGU-CS-VIL/DeepDPM#15]
How to you train a model on a custom dataset which only consists of images (and no labels)?

**Comment by meitarronen** [comment]
For training on custom datasets - please see [this](https://github.com/BGU-CS-VIL/DeepDPM/issues/3#issuecomment-1107815074) response to a similar question.

As we use the labels only for evaluations - you can create mock (fake) random labels and ignore the evaluation results. For faster training, you could also disable the evaluation functions.
