### ISSUE TITLE
Size exceed during training

### ISSUE THREAD

**Issue by CHUANG-L** [BGU-CS-VIL/DeepDPM#16]
gmm_k = MultivariateNormal(model_mus[k].double().to(device=self.device), model_covs[k].double().to(device=self.device))
IndexError: index 4 is out of bounds for dimension 0 with size 4

Hi,I would like to know why the size exceeds the problem when the algorithm changes the number of clusters k during training. How can I solve this problem? thank you very much.

**Comment by meitarronen** [comment]
@CHUANG-L In the last update of the code this bug has been fixed. Please let us know if it persists!
