### ISSUE TITLE
TensorOptions TypeError at 'embbeded_datasets.py', line 35

### ISSUE THREAD

**Issue by emilim** [BGU-CS-VIL/DeepDPM#20]
I am new to keras, so it's probably my error, but I can not find a solution in any forum, so I am asking here.
The error is:
`TypeError: expected TensorOptions(dtype=float, device=cpu, layout=Strided, requires_grad=false (default), pinned_memory=false (default), memory_format=(nullopt)) (got TensorOptions(dtype=unsigned char, device=cpu, layout=Strided, requires_grad=false (default), pinned_memory=false (default), memory_format=(nullopt)))`
When I run: _python DeepDPM.py --dataset MNIST_N2D_

**Comment by akramsanad** [comment]
On line 35 of embbeded_datasets.py
replace train_labels by :
train_labels = torch.Tensor(labels.to(torch.float)).cpu().float()

And it should work.
