### ISSUE TITLE
"Data" directory

### ISSUE THREAD

**Issue by akramsanad** [BGU-CS-VIL/DeepDPM#21]
I have raw data fairly similar to MNIST and i would like to train your model on it.
I'm quite new in ML and i don't really know how to put the name of my dataset as an argument and where to actually put my dataset . I've read the custom Dataset closed issues but i still don't grasp how to do it .

And also how i can save models and have checkpoints please i couldn't figure it out.
Thank you in advance to anyone who can help me

**Comment by meitarronen** [comment]
Hi,
DeepDPM operates in the feature space and not usually on the raw data.
You should first perform dimensionality reduction of your data using e.g. UMAP and then save the resulting features into "train_data.pt" tensors. Then, set the "--dir" flag to the directory that contains the saved embeddings, and DeepDPM will cluster them.
Please read the updated readme file in this repo for more information.
