### ISSUE TITLE
About the use of labels

### ISSUE THREAD

**Issue by alamie** [BGU-CS-VIL/DeepDPM#22]
Thank you very much for open-sourcing the code of your model 🎉 
Going through the `DeepDPM` code, I see that several methods rely on ground truth labels for data points.
Would it be possible to apply the `DeepDPM` model to a dataset in a fully _unsupervised_ way (no labels available)?

**Comment by alamie** [comment]
Apologies, I did not see at first that this question has been answered [here](https://github.com/BGU-CS-VIL/DeepDPM/issues/3#issuecomment-1107815074).

**Comment by antonioFlavio** [comment]
Hey @alamie did you find way to train the model with a fully unsupervised way without labels?

**Comment by antonioFlavio** [comment]
> Hey @alamie did you find way to train the model with a fully unsupervised way without labels?

I found the answer [here](https://github.com/BGU-CS-VIL/DeepDPM/issues/12)
