### ISSUE TITLE
`IndexError` when training on a custom dataset

### ISSUE THREAD

**Issue by alamie** [BGU-CS-VIL/DeepDPM#25]
I cloned the repository and trained a DeepDPM on a custom dataset (with pre-computed embeddings of dim 128).

I ran the `DeepDPM.py` file with `init_k=150`. At epoch 56 (after splitting clusters at epoch 55), I get the following error:

```python
line 237, in cluster_loss_function
    gmm_k = MultivariateNormal(model_mus[k].double().to(device=self.device), model_covs[k].double().to(device=self.device))
IndexError: index 150 is out of bounds for dimension 0 with size 150
```

After splitting, the model creates more clusters (156) than `model_mus` and `model_covs` can handle (150).
@meitarronen Please help, how can I deal with this issue?

**Comment by alamie** [comment]
@meitarronen @freifeld Up 🙏 Any idea?

**Comment by meitarronen** [comment]
@alamie we will upload an update soon with this bug fixed.

**Comment by meitarronen** [comment]
@alamie In the last update of the code this bug has been fixed. Please let us know if it persists!
