### ISSUE TITLE
Why did the first epoch run so long

### ISSUE THREAD

**Issue by liuyukid** [BGU-CS-VIL/DeepDPM#28]
[running kmeans]: 4it [00:03,  1.42it/s, center_shift=0.000000, iteration=5, tol=0.0
[running kmeans]: 5it [00:07,  1.55s/it, center_shift=0.000000, iteration=5, tol=0.000100]ting:   0%|                                            | 0/69 [00:00<?, ?it/s]
Epoch 1:  50%|█████████         | 69/138 [00:10<00:10,  6.70it/s, loss=1.96, v_num=]Evaluating...                                                                       
NMI : 0.017017041797800267, ARI: 0.007834735394701565, ACC: 0.1387, current K: 3
Epoch 1:  99%|████████████████▉| 137/138 [**07:30**<00:03,  3.29s/it, loss=1.96, v_num=Evaluating...100%|███████████████████████████████████| 69/69 [00:08<00:00,  7.05it/s]
Epoch 1: 100%|█████████████████| 138/138 [**07:42**<00:00,  3.35s/it, loss=1.96, v_num=]
Evaluating...
Epoch 2:  50%|█████████         | 69/138 [00:11<00:11,  5.87it/s, loss=1.81, v_num=]Evaluating...                                                                       
NMI : 0.27587234909394287, ARI: 0.10852441686412587, ACC: 0.20503, current K: 2
Epoch 2:  99%|████████████████▉| 137/138 [00:20<00:00,  6.63it/s, loss=1.81, v_num=Evaluating...100%|███████████████████████████████████| 69/69 [00:08<00:00,  7.09it/s]
Evaluating...
Epoch 3:  50%|█████████         | 69/138 [00:11<00:11,  5.82it/s, loss=1.64, v_num=]Evaluating...                                                                       
NMI : 0.3924139816776356, ARI: 0.17518072194919748, ACC: 0.21256, current K: 2
Epoch 3: 100%|█████████████████| 138/138 [00:20<00:00,  6.62it/s, loss=1.64, v_num=Evaluating...100%|███████████████████████████████████| 69/69 [00:08<00:00,  6.42it/s]

**Comment by meitarronen** [comment]
In the first epoch, we initialize the parameters of the network, e.g., the clusters parameters using K-means which might take some time. How much time does it take you and on which dataset? what is its size?
