### ISSUE TITLE
get similar gif in custom datasets

### ISSUE THREAD

**Issue by lijiaoyang** [BGU-CS-VIL/DeepDPM#29]
hi, if I want to get a similar gif in custom datasets , such as CIFAR10.
What should I do to get it?
I see the gif should get inputs data as 2D shape, so should I use PCA to get low dimension embedding?
thx!!

**Comment by meitarronen** [comment]
Hi, yes!
Basically, to create that giif you would need 2d data - you can try to perform dimensionality reduction to 2D and then follow the example we have on our code :)
You could use PCA, t-SNE or UMAP as an example.
