### ISSUE TITLE
How to generate .zip file as shown in the path of "\saved_models\ae_weights\" for a custom dataset?

### ISSUE THREAD

**Issue by ssuhanchen** [BGU-CS-VIL/DeepDPM#30]
Thank you for sharing your great work! I have tried the newest version package, it works for clustering benchmark datasets but there are still difficulties with my custom dataset. After preparing a custom dataset, the first thing seems to learn weights of an auto-encoder on the custom dataset and saving the corresponding .zip file in the path of "\saved_models\ae_weights\". In order to generate train_data.pt, we need the file of "make_embbedings.py" or "make_umap_embeddings.py" to do so. But I found that the "make_embbedings.py" has a parameter "--pretrain_path" and make_umap_embeddings.py has a parameter "--ae_pretrain_path" which means the weights of an auto-encoder should be prepared in advance. Could you please share the corresponding script or tell me how to do it in more detail. Looking forward to your guidance.

**Comment by meitarronen** [comment]
Hey, thanks for your interest!
DeepDPM runs on pretrained embeddings (e.g., train_data.pt).
One approach for generating these embeddings is using an autoencoder, where the embeddings are the latent features.
To do so, you can run the DeepDPM_alternations script where you can also pretrain the AE using the --pretrain and the --pretrain_epochs flags (the former to use pertaining and the latter to specify for how many epochs).
The AE weights will be saved under \saved_models\ae_weights.

If you already have a pretrained embeddings which you created using a separate autoencoder, you can do a forward pass on your data using your AE and save the encoder's output as train_data.pt and then use load it to the DeepDPM script.

Let us know if this helps!
Meitar

**Comment by ssuhanchen** [comment]
Thanks Dr. Meitar

Thank your for your kindly response and sorry to bother you again. I still cannot build up my AE model using my custom dataset. Please guide me again.
Base on your guidance, I have well set the flags of --pretrain and --pretrain_epochs in the "DeepDPM_alternations.py" script.
But when I set the flag --dataset to 'custom' in the "DeepDPM_alternations.py" script, the script loads the data by using data = CustomDataset(args) in /src/datasets.py in which the embeddings "train_data.pt", "train_labels.pt", "test_data.pt", and "test_labels.pt" need to be prepared in advance.
I can understand the embeddings of custom dataset should be generated using "make_embbedings.py" or "make_umap_embeddings.py".
However, the data loader of "make_embbedings.py" and "make_umap_embeddings.py" cannot load custom dataset and the process of getting the pre-trained auto-encoder weights is not provided in current version.

The above problems have caused the modeling progress to stagnate. Could you please guide me if it is convenient? I am eager to know how to build a deepDPM model step by step when I have a customized dataset and whose data structure is show in below. Thank you.

|__ dataset
|______ cats: [cat.0.jpg, cat.1.jpg, cat.2.jpg ....]
|______ dogs: [dog.0.jpg, dog.1.jpg, dog.2.jpg ...]
|______ rats: [rat.0.jpg, rat.1.jpg, rat.2.jpg ...]

**Comment by meitarronen** [comment]
Hi @ssuhanchen,
Both the make_embeddings and make_umap_embeddings scripts are assuming that there is an already pretrained Autoencoder (in the make embeddings script the embeddings are generated using a forward pass through the AE and and the make_umap_embedding there is a umap operation after the forward pass though the AE).

To create your own embeddings you could train an AE on your data and save its weights and then use the scripts above.
If you want to use our code for the AE training, you could use the DeepDPM_alternation script and set the --pretrain_epochs to the number of epochs you want to train your AE (e.g., 100).
If you want to use this script only for AE pretraining, you could set "number_of_ae_alternations" to 1 and then only AE pretraining and DeepDPM clustering will occur. You could also leave it at 3 and see maybe the alternation between the feature learning and clustering could improve the performance.

To save the learned AE weights, use the --save_checkpoints flag.

More generally, you could use any method for feature extraction and save the resulting embeddings (yourself, using torch.save) to the required train_data.pt and test_data.pt and run DeepDPM from there.

Hope this helps!
