### ISSUE TITLE
Size mismatch error when running the inference script on MNIST

### ISSUE THREAD

**Issue by hafsaEn** [BGU-CS-VIL/DeepDPM#37]
After training the model on the MNIST dataset, I used the following command  to do inference

`python -m scripts.DeepDPM_load_from_checkpoint.py --dataset MNIST --dir "./pretrained_embeddings/umap_embedded_datasets/MNIST"`

I specified the DIMENSION OF THE DATA to be  28 * 28 and added CHECKPOINT_PATH in the scripts\DeepDPM_load_from_checkpoint.py, but I still get the following error:

`Traceback (most recent call last):
  File "/home/hafsa/DeepDPM/DeepDPM_load_from_checkpoint.py", line 30, in <module>
    model = ClusterNetModel.load_from_checkpoint(
  File "/home/hafsa/.conda/envs/deepdpm/lib/python3.10/site-packages/pytorch_lightning/core/saving.py", line 157, in load_from_checkpoint
    model = cls._load_model_state(checkpoint, strict=strict, **kwargs)
  File "/home/hafsa/.conda/envs/deepdpm/lib/python3.10/site-packages/pytorch_lightning/core/saving.py", line 205, in _load_model_state
    model.load_state_dict(checkpoint['state_dict'], strict=strict)
  File "/home/hafsa/.conda/envs/deepdpm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1497, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ClusterNetModel:
	size mismatch for cluster_net.class_fc1.weight: copying a param with shape torch.Size([50, 10]) from checkpoint, the shape in current model is torch.Size([50, 784]).
	size mismatch for subclustering_net.class_fc1.weight: copying a param with shape torch.Size([50, 10]) from checkpoint, the shape in current model is torch.Size([50, 784]).`

Any idea on how to solve this issue ?

Thank you

**Comment by meitarronen** [comment]
Hey @hafsaEn!
Thanks for your interest!

If you trained our network on MNIST using the pretrained embeddings (e.g. using this command:
python DeepDPM.py --dataset MNIST --dir "./pretrained_embeddings/umap_embedded_datasets/MNIST"
, then the data dimensionality is 10 (and not the full 28*28 image)).

I added further clarification to the load_from_checkpoint script for future uses
