### ISSUE TITLE
Accuracy when K is unknown

### ISSUE THREAD

**Issue by ruizhaoz** [BGU-CS-VIL/DeepDPM#43]
When K is unknown, if the final k is not exactly class number, how the acc defined. From the code and paper, it seems to ignoring some prediced clusters (if K is larger than number of classes.). Is my underdstanding correct? For example number of class is 10 and final K is 15, then there will be 5 predicted cluster being ignored for computing the accuracy? Is that always true that the extra 5 classes contain very few number of data?

**Comment by meitarronen** [comment]
In computing accuracy, first, we compute the best "matching" between the gt partitioning and the predicted one and then calculate the accuracy using that. You can see the exact equation in the supplementary material.
So, if the inferred K is 11 and the GT K is 10, one cluster will be ignored in computing the accuracy. 
It is not always the case that, in your example, the extra 5 classes will contain very few data points (that depends on the matching algorithm, in our case the Hungarian matching algorithm), but it is usually the case...

**Comment by ruizhaoz** [comment]
Thanks! That makes sense!
