### ISSUE TITLE
no module named 'neptune.experiments'

### ISSUE THREAD

**Issue by zhangtzq** [BGU-CS-VIL/DeepDPM#56]
I use 'conda list' to check the module which has been installed. I find that I have installed the right version of package. But why am I still getting errors?
neptune-client            1.6.1              pyhd8ed1ab_0    conda-forge

**Comment by MeetPerfect** [comment]
Hello, me too, can you solve it? Thanks.

**Comment by MeetPerfect** [comment]
Hello，I'm using the version of neptune-client==0.16.1 in the requirements.txt file.
